set -g mouse on
setw -g mode-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g status-position bottom
set -g status-interval 5
set -g status-style "bg=black,fg=white"

set -g status-left-length 40
set -g status-left "#[fg=yellow]#H #[fg=green]#S #[default]"
set -g status-right "#[fg=cyan]%m-%d %H:%M #[fg=yellow]#H"

set -g pane-border-style "fg=brightgreen"
set -g pane-active-border-style "fg=green"

bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind x kill-pane
bind & kill-window
bind r source-file ~/.tmux.conf \; display "Config reloaded"
bind P display-popup -w 60% -h 60% -E "zsh -ic 'exec zsh'"

set -g set-titles on
set -g set-titles-string '#S'
set -g allow-passthrough on
set -g set-clipboard on
